service: books-api
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    CONFIG_BOOKS_TABLE: ${self:custom.tableNames.books}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - BooksTable
          - Arn
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-dynamodb-local
  - serverless-offline  # should be last in list
custom:
  defaultStage: dev
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  dynamodb:
    start:
      migrate: true
  tableNames:
    books: 'books'
resources:
  - ${file(resources/books-table.yml)}
package:
  exclude:
    - ".dynamodb/**"
    - ".idea/**"
